import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {SideNavBar} from "@/components/SideNavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: 'flex' }}>
        <SideNavBar />
        <div style={{ flex: 1, padding: '20px' }}>
          {children}
        </div>
      </body>
    </html>
  )
}
